service: spacy-layer

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: python3.8
  region: us-east-1

layers:
  spacy:
    package:
      artifact: en_core_web_sm.zip
    compatibleRuntimes:
      - python3.8

resources:
  Resources:
    SpacyLayerParameter:
      Type: AWS::SSM::Parameter
      Properties:
        Name: /spacy/${self:provider.stage}/layerARN
        Type: String
        Value: !Ref SpacyLambdaLayer

